import {
  getFeaturedMedia,
  getGallery,
  listAnnouncements,
  listClubAchievements,
  listClubEvents,
  listClubs,
  listGalleries,
  listGalleriesForTarget,
  listAchievements,
  listEvents,
  listPeople,
} from "./public";
import {
  listMyGalleries,
  listMyGalleryLinks,
  listMyLinkTargets,
  myClub,
} from "./scope";
import {
  listMySubmissions,
  submitClubAchievement,
  submitClubAnnouncement,
  submitClubAnnouncementUpdate,
  submitClubEvent,
  submitClubEventUpdate,
  submitClubProfileUpdate,
  submitGalleryCreate,
  submitGalleryItemCreate,
  submitGalleryItemUpdate,
  submitGalleryLinkCreate,
  submitGalleryLinkDelete,
  submitGalleryUpdate,
  submitAchievementCreate,
  submitEventCreate,
  submitPersonCreate,
  withdrawClubSubmission,
  withdrawGlobalSubmission,
} from "./submissions";

export const clubsRouter = {
  listClubs,
  listGalleries,
  getGallery,
  listGalleriesForTarget,
  getFeaturedMedia,
  listClubEvents,
  listClubAchievements,
  listAnnouncements,
  listEvents,
  listPeople,
  listAchievements,
  myClub,
  listMyGalleries,
  listMyGalleryLinks,
  listMyLinkTargets,
  submitClubEvent,
  submitClubAnnouncement,
  submitClubAchievement,
  submitClubEventUpdate,
  submitClubAnnouncementUpdate,
  submitClubProfileUpdate,
  submitGalleryCreate,
  submitGalleryUpdate,
  submitGalleryItemCreate,
  submitGalleryItemUpdate,
  submitGalleryLinkCreate,
  submitGalleryLinkDelete,
  submitPersonCreate,
  submitEventCreate,
  submitAchievementCreate,
  listMySubmissions,
  withdrawGlobalSubmission,
  withdrawClubSubmission,
};
