CREATE TABLE `student_subject_selection` (
	`id` text PRIMARY KEY,
	`student_id` text NOT NULL,
	`academic_year_id` text NOT NULL,
	`basket_category` text NOT NULL,
	`subject_key` text NOT NULL,
	`previous_selection_id` text,
	`superseded_at` integer,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	CONSTRAINT `fk_student_subject_selection_student_id_student_id_fk` FOREIGN KEY (`student_id`) REFERENCES `student`(`id`) ON DELETE CASCADE,
	CONSTRAINT `fk_student_subject_selection_academic_year_id_academic_year_id_fk` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_year`(`id`) ON DELETE CASCADE,
	CONSTRAINT `fk_student_subject_selection_previous_selection_id_student_subject_selection_id_fk` FOREIGN KEY (`previous_selection_id`) REFERENCES `student_subject_selection`(`id`) ON DELETE SET NULL
);
--> statement-breakpoint
ALTER TABLE `exam_type` ADD `grade_level` integer;--> statement-breakpoint
ALTER TABLE `academic_year` ADD `structure_version_key` text;--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_exam_type` (
	`id` text PRIMARY KEY,
	`academic_year_id` text NOT NULL,
	`name` text NOT NULL,
	`category` text NOT NULL,
	`grade_level` integer,
	`max_mark` integer DEFAULT 100 NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	CONSTRAINT `fk_exam_type_academic_year_id_academic_year_id_fk` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_year`(`id`) ON DELETE CASCADE,
	CONSTRAINT `exam_type_year_grade_name_unique` UNIQUE(`academic_year_id`,`grade_level`,`name`)
);
--> statement-breakpoint
INSERT INTO `__new_exam_type`(`id`, `academic_year_id`, `name`, `category`, `max_mark`, `sort_order`, `created_at`) SELECT `id`, `academic_year_id`, `name`, `category`, `max_mark`, `sort_order`, `created_at` FROM `exam_type`;--> statement-breakpoint
DROP TABLE `exam_type`;--> statement-breakpoint
ALTER TABLE `__new_exam_type` RENAME TO `exam_type`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `exam_type_year_idx` ON `exam_type` (`academic_year_id`);--> statement-breakpoint
CREATE INDEX `exam_type_category_idx` ON `exam_type` (`category`);--> statement-breakpoint
CREATE INDEX `exam_type_grade_idx` ON `exam_type` (`grade_level`);--> statement-breakpoint
CREATE INDEX `sss_student_idx` ON `student_subject_selection` (`student_id`);--> statement-breakpoint
CREATE INDEX `sss_year_idx` ON `student_subject_selection` (`academic_year_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `sss_active_unique` ON `student_subject_selection` (`student_id`,`academic_year_id`,`basket_category`) WHERE "student_subject_selection"."superseded_at" is null;--> statement-breakpoint
UPDATE `academic_year` SET `structure_version_key` = 'v1' WHERE `structure_version_key` IS NULL;--> statement-breakpoint
INSERT INTO `grade_subject_config` (`id`, `academic_year_id`, `grade_level`, `basket_category`, `subject_key`, `sort_order`, `created_at`)
SELECT lower(hex(randomblob(16))), ay.id, e.column1, e.column2, e.column3, e.column4, (cast(unixepoch('subsecond') * 1000 as integer))
FROM `academic_year` ay
CROSS JOIN (VALUES
		(1,'compulsory','motherTongue',0),
		(1,'compulsory','mathematics',1),
		(1,'compulsory','environmentRelatedActivities',2),
		(1,'compulsory','religion',3),
		(2,'compulsory','motherTongue',0),
		(2,'compulsory','mathematics',1),
		(2,'compulsory','environmentRelatedActivities',2),
		(2,'compulsory','religion',3),
		(3,'compulsory','motherTongue',0),
		(3,'compulsory','mathematics',1),
		(3,'compulsory','environmentRelatedActivities',2),
		(3,'compulsory','religion',3),
		(3,'compulsory','englishLanguage',4),
		(3,'compulsory','secondNationalLanguage',5),
		(4,'compulsory','motherTongue',0),
		(4,'compulsory','mathematics',1),
		(4,'compulsory','environmentRelatedActivities',2),
		(4,'compulsory','religion',3),
		(4,'compulsory','englishLanguage',4),
		(4,'compulsory','secondNationalLanguage',5),
		(5,'compulsory','motherTongue',0),
		(5,'compulsory','mathematics',1),
		(5,'compulsory','environmentRelatedActivities',2),
		(5,'compulsory','religion',3),
		(5,'compulsory','englishLanguage',4),
		(5,'compulsory','secondNationalLanguage',5),
		(6,'compulsory','religion',0),
		(6,'compulsory','motherTongue',1),
		(6,'compulsory','englishLanguage',2),
		(6,'compulsory','secondNationalLanguage',3),
		(6,'compulsory','mathematics',4),
		(6,'compulsory','science',5),
		(6,'compulsory','history',6),
		(6,'compulsory','geography',7),
		(6,'compulsory','civicEducation',8),
		(6,'compulsory','healthAndPhysicalEducation',9),
		(6,'compulsory','lifeCompetencies',10),
		(6,'compulsory','practicalTechnicalSkills',11),
		(6,'aesthetic','art',0),
		(6,'aesthetic','musicOriental',1),
		(6,'aesthetic','musicWestern',2),
		(6,'aesthetic','musicCarnatic',3),
		(6,'aesthetic','dancingIndigenous',4),
		(6,'aesthetic','dancingBharatha',5),
		(6,'aesthetic','dramaTheatreSinhala',6),
		(6,'aesthetic','dramaTheatreTamil',7),
		(6,'aesthetic','dramaTheatreEnglish',8),
		(7,'compulsory','religion',0),
		(7,'compulsory','motherTongue',1),
		(7,'compulsory','englishLanguage',2),
		(7,'compulsory','secondNationalLanguage',3),
		(7,'compulsory','mathematics',4),
		(7,'compulsory','science',5),
		(7,'compulsory','history',6),
		(7,'compulsory','geography',7),
		(7,'compulsory','civicEducation',8),
		(7,'compulsory','healthAndPhysicalEducation',9),
		(7,'compulsory','lifeCompetencies',10),
		(7,'compulsory','practicalTechnicalSkills',11),
		(7,'aesthetic','art',0),
		(7,'aesthetic','musicOriental',1),
		(7,'aesthetic','musicWestern',2),
		(7,'aesthetic','musicCarnatic',3),
		(7,'aesthetic','dancingIndigenous',4),
		(7,'aesthetic','dancingBharatha',5),
		(7,'aesthetic','dramaTheatreSinhala',6),
		(7,'aesthetic','dramaTheatreTamil',7),
		(7,'aesthetic','dramaTheatreEnglish',8),
		(8,'compulsory','religion',0),
		(8,'compulsory','motherTongue',1),
		(8,'compulsory','englishLanguage',2),
		(8,'compulsory','secondNationalLanguage',3),
		(8,'compulsory','mathematics',4),
		(8,'compulsory','science',5),
		(8,'compulsory','history',6),
		(8,'compulsory','geography',7),
		(8,'compulsory','civicEducation',8),
		(8,'compulsory','healthAndPhysicalEducation',9),
		(8,'compulsory','lifeCompetencies',10),
		(8,'compulsory','practicalTechnicalSkills',11),
		(8,'aesthetic','art',0),
		(8,'aesthetic','musicOriental',1),
		(8,'aesthetic','musicWestern',2),
		(8,'aesthetic','musicCarnatic',3),
		(8,'aesthetic','dancingIndigenous',4),
		(8,'aesthetic','dancingBharatha',5),
		(8,'aesthetic','dramaTheatreSinhala',6),
		(8,'aesthetic','dramaTheatreTamil',7),
		(8,'aesthetic','dramaTheatreEnglish',8),
		(9,'compulsory','religion',0),
		(9,'compulsory','motherTongue',1),
		(9,'compulsory','englishLanguage',2),
		(9,'compulsory','secondNationalLanguage',3),
		(9,'compulsory','mathematics',4),
		(9,'compulsory','science',5),
		(9,'compulsory','history',6),
		(9,'compulsory','geography',7),
		(9,'compulsory','civicEducation',8),
		(9,'compulsory','healthAndPhysicalEducation',9),
		(9,'compulsory','lifeCompetencies',10),
		(9,'compulsory','practicalTechnicalSkills',11),
		(9,'aesthetic','art',0),
		(9,'aesthetic','musicOriental',1),
		(9,'aesthetic','musicWestern',2),
		(9,'aesthetic','musicCarnatic',3),
		(9,'aesthetic','dancingIndigenous',4),
		(9,'aesthetic','dancingBharatha',5),
		(9,'aesthetic','dramaTheatreSinhala',6),
		(9,'aesthetic','dramaTheatreTamil',7),
		(9,'aesthetic','dramaTheatreEnglish',8),
		(10,'compulsory','englishLanguage',0),
		(10,'compulsory','mathematics',1),
		(10,'compulsory','science',2),
		(10,'compulsory','history',3),
		(10,'religion','buddhism',0),
		(10,'religion','saivanery',1),
		(10,'religion','catholicism',2),
		(10,'religion','christianity',3),
		(10,'religion','islam',4),
		(10,'motherTongue','sinhalaLanguageAndLiterature',0),
		(10,'motherTongue','tamilLanguageAndLiterature',1),
		(10,'languagesHumanities','businessAccountingStudies',0),
		(10,'languagesHumanities','geography',1),
		(10,'languagesHumanities','civicEducation',2),
		(10,'languagesHumanities','entrepreneurshipStudies',3),
		(10,'languagesHumanities','secondLanguageSinhala',4),
		(10,'languagesHumanities','secondLanguageTamil',5),
		(10,'languagesHumanities','pali',6),
		(10,'languagesHumanities','sanskrit',7),
		(10,'languagesHumanities','french',8),
		(10,'languagesHumanities','german',9),
		(10,'languagesHumanities','hindi',10),
		(10,'languagesHumanities','japanese',11),
		(10,'languagesHumanities','arabic',12),
		(10,'languagesHumanities','korean',13),
		(10,'languagesHumanities','chinese',14),
		(10,'languagesHumanities','russian',15),
		(10,'aestheticsArts','musicOriental',0),
		(10,'aestheticsArts','musicWestern',1),
		(10,'aestheticsArts','musicCarnatic',2),
		(10,'aestheticsArts','art',3),
		(10,'aestheticsArts','dancingIndigenous',4),
		(10,'aestheticsArts','dancingBharatha',5),
		(10,'aestheticsArts','appreciationEnglishLiteraryTexts',6),
		(10,'aestheticsArts','appreciationSinhalaLiteraryTexts',7),
		(10,'aestheticsArts','appreciationTamilLiteraryTexts',8),
		(10,'aestheticsArts','appreciationArabicLiteraryTexts',9),
		(10,'aestheticsArts','dramaTheatreSinhala',10),
		(10,'aestheticsArts','dramaTheatreTamil',11),
		(10,'aestheticsArts','dramaTheatreEnglish',12),
		(10,'technicalVocational','ict',0),
		(10,'technicalVocational','agricultureFoodTechnology',1),
		(10,'technicalVocational','aquaticBioresourcesTechnology',2),
		(10,'technicalVocational','artsCrafts',3),
		(10,'technicalVocational','homeEconomics',4),
		(10,'technicalVocational','healthPhysicalEducation',5),
		(10,'technicalVocational','communicationMediaStudies',6),
		(10,'technicalVocational','designConstructionTechnology',7),
		(10,'technicalVocational','designMechanicalTechnology',8),
		(10,'technicalVocational','designElectricalElectronicTechnology',9),
		(10,'technicalVocational','electronicWritingShorthandSinhala',10),
		(10,'technicalVocational','electronicWritingShorthandTamil',11),
		(10,'technicalVocational','electronicWritingShorthandEnglish',12),
		(11,'compulsory','englishLanguage',0),
		(11,'compulsory','mathematics',1),
		(11,'compulsory','science',2),
		(11,'compulsory','history',3),
		(11,'religion','buddhism',0),
		(11,'religion','saivanery',1),
		(11,'religion','catholicism',2),
		(11,'religion','christianity',3),
		(11,'religion','islam',4),
		(11,'motherTongue','sinhalaLanguageAndLiterature',0),
		(11,'motherTongue','tamilLanguageAndLiterature',1),
		(11,'languagesHumanities','businessAccountingStudies',0),
		(11,'languagesHumanities','geography',1),
		(11,'languagesHumanities','civicEducation',2),
		(11,'languagesHumanities','entrepreneurshipStudies',3),
		(11,'languagesHumanities','secondLanguageSinhala',4),
		(11,'languagesHumanities','secondLanguageTamil',5),
		(11,'languagesHumanities','pali',6),
		(11,'languagesHumanities','sanskrit',7),
		(11,'languagesHumanities','french',8),
		(11,'languagesHumanities','german',9),
		(11,'languagesHumanities','hindi',10),
		(11,'languagesHumanities','japanese',11),
		(11,'languagesHumanities','arabic',12),
		(11,'languagesHumanities','korean',13),
		(11,'languagesHumanities','chinese',14),
		(11,'languagesHumanities','russian',15),
		(11,'aestheticsArts','musicOriental',0),
		(11,'aestheticsArts','musicWestern',1),
		(11,'aestheticsArts','musicCarnatic',2),
		(11,'aestheticsArts','art',3),
		(11,'aestheticsArts','dancingIndigenous',4),
		(11,'aestheticsArts','dancingBharatha',5),
		(11,'aestheticsArts','appreciationEnglishLiteraryTexts',6),
		(11,'aestheticsArts','appreciationSinhalaLiteraryTexts',7),
		(11,'aestheticsArts','appreciationTamilLiteraryTexts',8),
		(11,'aestheticsArts','appreciationArabicLiteraryTexts',9),
		(11,'aestheticsArts','dramaTheatreSinhala',10),
		(11,'aestheticsArts','dramaTheatreTamil',11),
		(11,'aestheticsArts','dramaTheatreEnglish',12),
		(11,'technicalVocational','ict',0),
		(11,'technicalVocational','agricultureFoodTechnology',1),
		(11,'technicalVocational','aquaticBioresourcesTechnology',2),
		(11,'technicalVocational','artsCrafts',3),
		(11,'technicalVocational','homeEconomics',4),
		(11,'technicalVocational','healthPhysicalEducation',5),
		(11,'technicalVocational','communicationMediaStudies',6),
		(11,'technicalVocational','designConstructionTechnology',7),
		(11,'technicalVocational','designMechanicalTechnology',8),
		(11,'technicalVocational','designElectricalElectronicTechnology',9),
		(11,'technicalVocational','electronicWritingShorthandSinhala',10),
		(11,'technicalVocational','electronicWritingShorthandTamil',11),
		(11,'technicalVocational','electronicWritingShorthandEnglish',12),
		(12,'compulsory','commonGeneralTest',0),
		(12,'compulsory','generalEnglish',1),
		(12,'bioScience','biology',0),
		(12,'bioScience','chemistry',1),
		(12,'bioScience','physics',2),
		(12,'bioScience','agriculturalScience',3),
		(12,'bioScience','higherMathematics',4),
		(12,'physicalScience','combinedMathematics',0),
		(12,'physicalScience','physics',1),
		(12,'physicalScience','chemistry',2),
		(12,'physicalScience','ict',3),
		(12,'physicalScience','higherMathematics',4),
		(12,'commerce','accounting',0),
		(12,'commerce','businessStudies',1),
		(12,'commerce','economics',2),
		(12,'commerce','businessStatistics',3),
		(12,'commerce','ict',4),
		(12,'commerce','geography',5),
		(12,'arts','buddhism',0),
		(12,'arts','hinduism',1),
		(12,'arts','christianity',2),
		(12,'arts','islam',3),
		(12,'arts','buddhistCivilization',4),
		(12,'arts','hinduCivilization',5),
		(12,'arts','christianCivilization',6),
		(12,'arts','islamicCivilization',7),
		(12,'arts','greekAndRomanCivilization',8),
		(12,'arts','politicalScience',9),
		(12,'arts','history',10),
		(12,'arts','geography',11),
		(12,'arts','logicAndScientificMethod',12),
		(12,'arts','economics',13),
		(12,'arts','agriculturalScience',14),
		(12,'arts','sinhala',15),
		(12,'arts','tamil',16),
		(12,'arts','english',17),
		(12,'arts','pali',18),
		(12,'arts','sanskrit',19),
		(12,'arts','arabic',20),
		(12,'arts','hindi',21),
		(12,'arts','french',22),
		(12,'arts','german',23),
		(12,'arts','russian',24),
		(12,'arts','chinese',25),
		(12,'arts','japanese',26),
		(12,'arts','korean',27),
		(12,'arts','malay',28),
		(12,'arts','homeEconomics',29),
		(12,'arts','dancingIndigenous',30),
		(12,'arts','dancingBharatha',31),
		(12,'arts','musicOriental',32),
		(12,'arts','musicCarnatic',33),
		(12,'arts','musicWestern',34),
		(12,'arts','art',35),
		(12,'arts','dramaTheatreSinhala',36),
		(12,'arts','dramaTheatreTamil',37),
		(12,'arts','dramaTheatreEnglish',38),
		(12,'arts','communicationMediaStudies',39),
		(13,'compulsory','commonGeneralTest',0),
		(13,'compulsory','generalEnglish',1),
		(13,'bioScience','biology',0),
		(13,'bioScience','chemistry',1),
		(13,'bioScience','physics',2),
		(13,'bioScience','agriculturalScience',3),
		(13,'bioScience','higherMathematics',4),
		(13,'physicalScience','combinedMathematics',0),
		(13,'physicalScience','physics',1),
		(13,'physicalScience','chemistry',2),
		(13,'physicalScience','ict',3),
		(13,'physicalScience','higherMathematics',4),
		(13,'commerce','accounting',0),
		(13,'commerce','businessStudies',1),
		(13,'commerce','economics',2),
		(13,'commerce','businessStatistics',3),
		(13,'commerce','ict',4),
		(13,'commerce','geography',5),
		(13,'arts','buddhism',0),
		(13,'arts','hinduism',1),
		(13,'arts','christianity',2),
		(13,'arts','islam',3),
		(13,'arts','buddhistCivilization',4),
		(13,'arts','hinduCivilization',5),
		(13,'arts','christianCivilization',6),
		(13,'arts','islamicCivilization',7),
		(13,'arts','greekAndRomanCivilization',8),
		(13,'arts','politicalScience',9),
		(13,'arts','history',10),
		(13,'arts','geography',11),
		(13,'arts','logicAndScientificMethod',12),
		(13,'arts','economics',13),
		(13,'arts','agriculturalScience',14),
		(13,'arts','sinhala',15),
		(13,'arts','tamil',16),
		(13,'arts','english',17),
		(13,'arts','pali',18),
		(13,'arts','sanskrit',19),
		(13,'arts','arabic',20),
		(13,'arts','hindi',21),
		(13,'arts','french',22),
		(13,'arts','german',23),
		(13,'arts','russian',24),
		(13,'arts','chinese',25),
		(13,'arts','japanese',26),
		(13,'arts','korean',27),
		(13,'arts','malay',28),
		(13,'arts','homeEconomics',29),
		(13,'arts','dancingIndigenous',30),
		(13,'arts','dancingBharatha',31),
		(13,'arts','musicOriental',32),
		(13,'arts','musicCarnatic',33),
		(13,'arts','musicWestern',34),
		(13,'arts','art',35),
		(13,'arts','dramaTheatreSinhala',36),
		(13,'arts','dramaTheatreTamil',37),
		(13,'arts','dramaTheatreEnglish',38),
		(13,'arts','communicationMediaStudies',39)
) AS e
WHERE NOT EXISTS (SELECT 1 FROM `grade_subject_config` g WHERE g.academic_year_id = ay.id);
